//    Chromis POS  - The New Face of Open Source POS
//    Copyright (c) (c) 2015-2016
//    http://www.chromis.co.uk
//
//    This file is part of Chromis POS
//
//     Chromis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Chromis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Chromis POS.  If not, see <http://www.gnu.org/licenses/>.
package uk.chromis.pos.payment;

import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import uk.chromis.pos.customers.CustomerInfoExt;
import uk.chromis.pos.forms.AppConfig;
import uk.chromis.pos.forms.AppLocal;
import uk.chromis.pos.forms.AppView;

/**
 *
 * @author adrianromero
 */
public class JPaymentMagcard extends javax.swing.JPanel implements JPaymentInterface {

    private PaymentPanel m_cardpanel;
    private final PaymentGateway m_paymentgateway;
    private final JPaymentNotifier m_notifier;
    private String transaction;

    public JPaymentMagcard(AppView app, JPaymentNotifier notifier) {

        initComponents();
        m_notifier = notifier;
        m_paymentgateway = PaymentGatewayFac.getPaymentGateway();

        if (m_paymentgateway == null) {
            jlblMessage.setText(AppLocal.getIntString("message.nopaymentgateway"));
        } else {            
            m_cardpanel = PaymentPanelFac.getPaymentPanel(AppConfig.getInstance().getProperty("payment.magcardreader"), notifier);
            add(m_cardpanel.getComponent(), BorderLayout.CENTER);
            jlblMessage.setText(null);           
        }
    }

    @Override
    public void activate(CustomerInfoExt customerext, double dTotal, String transID) {
        this.transaction = transID;

        if (m_cardpanel == null) {
            jlblMessage.setText(AppLocal.getIntString("message.nopaymentgateway"));
            m_notifier.setStatus(false, false);
        } else {
            jlblMessage.setText(null);
            m_cardpanel.activate(transaction, dTotal);
            // The cardpanel sets the status
        }
    }

    @Override
    public PaymentInfo executePayment() {

        jlblMessage.setText(null);

        PaymentInfoMagcard payinfo = m_cardpanel.getPaymentInfoMagcard();
// this msg shows but only after transaction state returned
//        jlblMessage.setText("Processing Transaction " + payinfo.getTransactionID() + "\n Please Wait...");
      //  revalidate();

// Go to Payment gateway
        m_paymentgateway.execute(payinfo);

        if (payinfo.isPaymentOK()) {
//            jlblMessage.setText("Transaction ID: " + payinfo.getTransactionID() + "APPROVED!");
//            JOptionPane.showMessageDialog(getRootPane(), "Transaction APPROVED!", "Card Payment", 
//                    JOptionPane.PLAIN_MESSAGE);              
//          //  revalidate();            
            return payinfo;
        } else {
            return null;
        }

    }

    /**
     *
     * @return
     */
    @Override
    public Component getComponent() {
        return this;
    }

    /**
     *
     * @param transid
     */
    public void setTransaction(String transid) {
        transaction = transid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblMessage = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(300, 40));
        setPreferredSize(new java.awt.Dimension(300, 40));
        setLayout(new java.awt.BorderLayout());

        jlblMessage.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblMessage.setText("jLabel1");
        jlblMessage.setMaximumSize(new java.awt.Dimension(46, 25));
        jlblMessage.setMinimumSize(new java.awt.Dimension(46, 25));
        jlblMessage.setPreferredSize(new java.awt.Dimension(46, 25));
        add(jlblMessage, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblMessage;
    // End of variables declaration//GEN-END:variables

}
